### ISSUE TITLE
Show date of creation in posts

### ISSUE THREAD

**Issue by pixelmord** [zoonk/web#29]
**Is your feature request related to a problem? Please describe.**
For me it is really important for context and to judge relevancy of articles and posts to be able to see the date of when the text was authored

**Describe the solution you'd like**
At a minimum I would love to see the date on the detail page in the hero section

**Comment by wceolin** [comment]
Thanks for the suggestion, @pixelmord.

I haven't implemented it yet because some post categories (e.g. lessons, books, courses, etc.) are meant to be collaborative (similar to Wikipedia: everyone can edit and improve them). For those, a creation date doesn't make much sense as they're meant to be always up-to-date (e.g. we don't see the creation data on Wikipedia articles).

However, displaying a creation date does make sense for non-collaborative categories (e.g. posts and questions). I just want to make clearer the distinction between collaborative (anyone can edit) and non-collaborative (only the author can edit) posts before I implement it.

**Comment by wceolin** [comment]
@pixelmord Thanks again for suggesting this feature. It was just released on [v0.7.1](https://github.com/zoonk/web/releases/tag/v0.7.1).
